#ifndef SINGLEAPPLICATION_GLOBAL_H
#define SINGLEAPPLICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SINGLEAPPLICATION_LIBRARY)
#  define SINGLEAPPLICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SINGLEAPPLICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SINGLEAPPLICATION_GLOBAL_H
